/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    HelloText: typeof import('./src/components/HelloText.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InteractionToolbar: typeof import('./src/components/InteractionToolbar.vue')['default']
  }
}
